### ISSUE TITLE
PyInstaller

### ISSUE THREAD

**Issue by Siecje** [Siecje/qml-testing#1]
Version: `3.2`

When I run `dist/main.exe` I get an error window with

```
Failed to execute script pyi_rth_qt5plugins
```

Command: `pyinstaller.exe --onefile --windowed main.py`

Run from `Git Bash` on `Windows 10.`

``` shell
cody@DESKTOP-INHV1TD MINGW64 ~/Desktop/qml-testing (pyinstaller)
$ pyinstaller.exe --onefile --windowed main.py
2438 INFO: PyInstaller: 3.2
2445 INFO: Python: 3.5.2
2446 INFO: Platform: Windows-10-10.0.14393-SP0
2452 INFO: wrote C:\Users\cody\Desktop\qml-testing\main.spec
2465 INFO: UPX is not available.
2467 INFO: Extending PYTHONPATH with paths
['C:\\Users\\cody\\Desktop\\qml-testing',
 'C:\\Users\\cody\\Desktop\\qml-testing']
2468 INFO: checking Analysis
2468 INFO: Building Analysis because out00-Analysis.toc is non existent
2468 INFO: Initializing module dependency graph...
2477 INFO: Initializing module graph hooks...
2575 INFO: Analyzing base_library.zip ...
11281 INFO: running Analysis out00-Analysis.toc
11903 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-stdio-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12013 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-math-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12025 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-runtime-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12030 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-heap-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12033 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-locale-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12134 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-string-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12139 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-conio-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12145 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-process-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12158 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-convert-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12167 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-time-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12175 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-filesystem-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12179 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-environment-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
12183 INFO: Caching module hooks...
12267 INFO: Analyzing C:\Users\cody\Desktop\qml-testing\main.py
12383 INFO: Loading module hooks...
12383 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
13227 INFO: Loading module hook "hook-xml.py"...
13694 INFO: Loading module hook "hook-PyQt5.py"...
13740 INFO: Loading module hook "hook-pydoc.py"...
13765 INFO: Loading module hook "hook-PyQt5.Qt.py"...
13774 INFO: Loading module hook "hook-PyQt5.QtQml.py"...
13784 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
13875 INFO: Loading module hook "hook-encodings.py"...
13887 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
13950 INFO: Loading module hook "hook-PyQt5.QtNetwork.py"...
14012 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
14053 INFO: Looking for ctypes DLLs
14068 INFO: Analyzing run-time hooks ...
14072 INFO: Including run-time hook 'pyi_rth_qt5.py'
14095 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
14119 INFO: Looking for dynamic libraries
15879 WARNING: lib not found: Qt5PrintSupport.dll dependency of C:\users\cody\an                                                                                                                                  aconda3\lib\site-packages\PyQt5\Qt\plugins\printsupport\windowsprintersupport.dl                                                                                                                                  l
16213 WARNING: lib not found: Qt5Svg.dll dependency of C:\users\cody\anaconda3\l                                                                                                                                  ib\site-packages\PyQt5\Qt\plugins\iconengines\qsvgicon.dll
16791 WARNING: lib not found: Qt5Svg.dll dependency of C:\users\cody\anaconda3\l                                                                                                                                  ib\site-packages\PyQt5\Qt\plugins\imageformats\qsvg.dll
17156 WARNING: lib not found: Qt5Network.dll dependency of C:\users\cody\anacond                                                                                                                                  a3\lib\site-packages\PyQt5\Qt\plugins\bearer\qnativewifibearer.dll
17788 WARNING: lib not found: Qt5Network.dll dependency of C:\users\cody\anacond                                                                                                                                  a3\lib\site-packages\PyQt5\Qt\plugins\bearer\qgenericbearer.dll
21552 WARNING: lib not found: Qt5Qml.dll dependency of c:\users\cody\anaconda3\l                                                                                                                                  ib\site-packages\PyQt5\QtQml.pyd
22193 WARNING: lib not found: Qt5Network.dll dependency of c:\users\cody\anacond                                                                                                                                  a3\lib\site-packages\PyQt5\QtNetwork.pyd
24543 WARNING: lib not found: Qt5PrintSupport.dll dependency of c:\users\cody\an                                                                                                                                  aconda3\lib\site-packages\PyQt5\QtPrintSupport.pyd
30283 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-utility-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
48064 WARNING: Can not get binary dependencies for file: c:\users\cody\anaconda3                                                                                                                                  \api-ms-win-crt-multibyte-l1-1-0.dll
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 695, in getImports
    return _getImports_pe(pth)
  File "c:\users\cody\anaconda3\lib\site-packages\PyInstaller\depend\bindepend.p                                                                                                                                  y", line 122, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
48065 WARNING: Attempted to add Python module twice with different upper/lowerca                                                                                                                                  ses: PyQt5.QtGui
48065 WARNING: Attempted to add Python module twice with different upper/lowerca                                                                                                                                  ses: PyQt5.QtQml
48065 WARNING: Attempted to add Python module twice with different upper/lowerca                                                                                                                                  ses: PyQt5.QtNetwork
48065 WARNING: Attempted to add Python module twice with different upper/lowerca                                                                                                                                  ses: PyQt5.QtCore
48065 WARNING: Attempted to add Python module twice with different upper/lowerca                                                                                                                                  ses: PyQt5.Qt
48065 WARNING: Attempted to add Python module twice with different upper/lowerca                                                                                                                                  ses: PyQt5.QtPrintSupport
48065 WARNING: Attempted to add Python module twice with different upper/lowerca                                                                                                                                  ses: PyQt5.QtWidgets
48066 INFO: Looking for eggs
48066 INFO: Using Python library c:\users\cody\anaconda3\python35.dll
48066 INFO: Found binding redirects:
[]
48078 INFO: Warnings written to C:\Users\cody\Desktop\qml-testing\build\main\war                                                                                                                                  nmain.txt
48172 INFO: checking PYZ
48173 INFO: Building PYZ because out00-PYZ.toc is non existent
48173 INFO: Building PYZ (ZlibArchive) C:\Users\cody\Desktop\qml-testing\build\m                                                                                                                                  ain\out00-PYZ.pyz
48857 INFO: checking PKG
48857 INFO: Building PKG because out00-PKG.toc is non existent
48858 INFO: Building PKG (CArchive) out00-PKG.pkg
58754 INFO: Bootloader c:\users\cody\anaconda3\lib\site-packages\PyInstaller\boo                                                                                                                                  tloader\Windows-64bit\runw.exe
58754 INFO: checking EXE
58754 INFO: Building EXE because out00-EXE.toc is non existent
58754 INFO: Building EXE from out00-EXE.toc
58772 INFO: Appending archive to EXE C:\Users\cody\Desktop\qml-testing\dist\main                                                                                                                                  .exe
```

**Comment by ebadali** [comment]
Getting Same Error. 
I am using anaconda 3.5 with Qt5 and pyinstaller 3.2.

**Comment by ZLeopard** [comment]
sometimes maybe the location is uncertain, So the pyinstaller can't find the paths to PyQt5.So you can use this command to add the paths.

> pyinstaller --paths D:\Python\Lib\site-packages\PyQt5\Qt\bin -F -w ***.py

**Comment by woshihuo12** [comment]
thanks. pyinstaller --paths D:\Python\Lib\site-packages\PyQt5\Qt\bin -F -w ***.py  solved my problem..

**Comment by woshihuo12** [comment]
and i put the "D:\Python\Lib\site-packages\PyQt5\Qt\bin" to Path settting.

**Comment by Siecje** [comment]
I get the same error. 

This is what I am running from `Git Bash`

```shell
$ pyinstaller.exe --paths C:\Users\cody\Anaconda3\Lib\site-package\PyQt5\Qt\bin -F -w ***.py main.py
```

I can't seem to have the `--paths` in `Command Prompt`.

**Comment by Siecje** [comment]
With `pyinstaller.exe --paths C:\Users\IEUser\Anaconda3\Lib\site-packages\PyQt5\Qt\bin -F -w main.py`


I get a 16MB dist\main.exe file which does launch.

With `pyinstaller.exe --paths C:\Users\IEUser\Anaconda3\Lib\site-packages\PyQt5\Qt\bin -F -w ***.py`
```
Traceback (most recent call last):
  File "c:\users\ieuser\anaconda3\lib\runpy.py", line 184, in _run_module_as_mai
n
    "__main__", mod_spec)
  File "c:\users\ieuser\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\IEUser\Anaconda3\Scripts\pyinstaller.exe\__main__.py", line 9,
in <module>
  File "c:\users\ieuser\anaconda3\lib\site-packages\PyInstaller\__main__.py", li
ne 88, in run
    spec_file = run_makespec(**vars(args))
  File "c:\users\ieuser\anaconda3\lib\site-packages\PyInstaller\__main__.py", li
ne 40, in run_makespec
    spec_file = PyInstaller.building.makespec.main(filenames, **opts)
  File "c:\users\ieuser\anaconda3\lib\site-packages\PyInstaller\building\makespe
c.py", line 372, in main
    specfile = open(specfnm, 'w')
OSError: [Errno 22] Invalid argument: 'C:\\Users\\IEUser\\Downloads\\qml-testing
-master\\qml-testing-master\\***.spec'
```

**Comment by Siecje** [comment]
When I run `main.exe` in `build\main\` 

I get

```shell
Error loading Python DLL: C:\Users\Cody\Downloads\qml-testing-master\qml-testing-master\build\main\python36.dll (error code 126)
```

When I run `main.exe` in `dist\main\` 

I get

```shell
Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", line 46, in <module>
  File "c:\users\cody\downloads\qml-testing-master\qml-testing-master\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ImportError: DLL load failed: The specified module could not be found.
Failed to execute script pyi_rth_qt5plugins
```

If I run with `--paths` as above I get many lines of output complaining about missing `api-ms-win-crt-heap-l1-1-0.dll` and others. I do get a `dist\main.exe` instead of `dist\main\main.exe` but it doesn't open and there is no console output when I run it from `cmd`.

**Comment by Siecje** [comment]
Here is the qutebrowser .spec file for future reference 

https://github.com/qutebrowser/qutebrowser/blob/eaecfe5882f59abaecabb688340c88b8638f4b1b/misc/qutebrowser.spec

And another PyInstaller reference 

https://github.com/altendky/st/blob/895d684cac06c7f330de40d1a76490a336ce68c7/appveyor.yml

**Comment by Siecje** [comment]
Using PyInstaller to create an executable is now working!
